### PR TITLE
Fix mode start_proc, generate missing init and start files.

### PR DESCRIPTION
**Pull request by samwillis**
Hi @divyenduz,

pllv8ify looks awesome! I've been playing with it and found bug where with the start_proc mode it wasn't generating the init and start files.

This pull fixes it, first it changes the typo `.concat` for a `.push` to add the files. It then fixes a bug I found where those files names were having the scopePrefix added twice.

Looking back at the history I can't work out when it stopped working, but suspicious it may be when there was a massive refactor last year. I think maybe as the example dist folders are not deleted when rebuilt it's not obvious.

Sam

### CODE REVIEW

**Comment by samwillis** [comment]
Although this is generating sql that matches that in the examples, I just tested it I think there may be a bug. Will take another look tomorrow.

**Comment by divyenduz** [comment]
Thanks for taking the time 🙌🏼, I clearly need more tests. The examples are also poor man's tests, so you can really run 

`yarn example:hello-start_proc` 

to see the output and compare. Thanks again for raising this PR!

**Comment by samwillis** [comment]
Just taken another look, it is all working ok, was my mistaken understanding on how `SET plv8.start_proc = plv8ify_init;` works.

**Comment by divyenduz** [comment]
Thanks for the contribution ✅

**Comment by divyenduz** [comment]
This is published in 0.0.41

**Pull request merged**
